---
- hosts: all
  become: yes
  tasks:
    - name: Mettre a jour le systeme
      yum: 
        name: '*'
        state: latest

    - name: changer la timezone
      shell: timedatectl set-timezone America/New_York

    - name: Installer ntp
      yum: 
        name: ntp 
        state: present 
        update_cache: yes
        
    - name: S'assurer que NTP est activé
      service:
        name: ntpd
        state: started
        enabled: yes