---
- hosts: all
  become: yes
  tasks:
    - name: Mettre a jour le systeme
      yum: name=* state=latest
    - name: S'assurer que NTP est installé
      yum: 
        name: ntp
        state: present
    - name: S'assurer que NTP est activé
      service:
        name: ntpd
        state: started
        enabled: yes