---
- hosts: all
  become: yes
  tasks:

    - name: Mettre a jour le systeme
      apt:
        name: "*"
        state: latest

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: deploy nginx docker container
      docker_container:
        image: nginx:stable
        name: nginx
        state: started
        auto_remove: true
        ports:
          - "8080:80"