- hosts: localhost
  vars_files: vars.yml
  tasks:

  - name: create a new droplet assigning the key
    digital_ocean_droplet:
      name: "{{ item }}"
      oauth_token: "{{ digital_ocean_token }}"
      size: "{{ droplet_size }}"
      region: "{{ droplet_region }}"
      image: "{{ droplet_image }}"
      wait_timeout: 600
      unique_name: yes
      ssh_keys: ["{{ sshkey_result.data.ssh_key.id }}"]      
      state: present
    with_inventory_hostnames:
      - web
    register: droplet_result

  - name: save ip and hostname to local hosts file /etc/hosts
    become: yes
    lineinfile:
      path: /etc/hosts
      regexp: '.*{{ item.data.droplet.name }}$'
      line: "{{ item.data.ip_address }}  {{ item.data.droplet.name }}"
    with_items: "{{ droplet_result.results }}"